title: Máté Szmetán
#logo: /assets/img/headshot_circle.png
description: 
Education
- Pannon Egyetem Veszprém - International Buisness Economics (2021-)
- Google Data Analytics (2024)
- Vetési Albert Gimnázium Veszprém (2017-2021)
#show_downloads: true
theme: jekyll-theme-minimal
